#!/usr/bin/env python3

import os, json

secretbuddy_data = json.loads(os.getenv("SECRETBUDDY_ENV"))

env_var_name = 'SECRETBUDDY_ENV'

# Get the environment variable value
env_var_value = os.getenv(env_var_name)


try:
        # Parse the JSON string into a Python dictionary
        json_value = json.loads(env_var_value)
        print(f"The value of '{env_var_name}' as JSON is:")
        print(json.dumps(json_value, indent=4))  # Pretty-print the JSON
except json.JSONDecodeError as e:
        print(f"Error decoding JSON from environment variable '{env_var_name}': {e}")

for k, v in secretbuddy_data["current"].items():
    env_value = os.getenv(k)
    if v == env_value:
        print(f"ok {k}")
    else:
        print(f"fail {k}, expected {env_value}, got {v}")

