#!/usr/bin/env python3

import os, json
import sys
import re

CYAN = "\033[36m"
RESET = "\033[0m"

# --------------------------------------------------------------------------------------------------
# function to anonimize the value by returning only the first 4 characters
# followed by "..."
def anonim(input_string):
    return input_string[:4] + "..."
# --------------------------------------------------------------------------------------------------
# check if the environment variable SECRETBUDDY_ENV is set and not empty
# and the JSON is valid
secretbuddy_env_var = "SECRETBUDDY_ENV"
secretbuddy_data = os.getenv(secretbuddy_env_var)
if not secretbuddy_data:
    print(f"{secretbuddy_env_var} is not set or is an empty string.")
    sys.exit(1)

try:
  secretbuddy_data_json = json.loads(secretbuddy_data)
except json.JSONDecodeError as e:
  print(f"Error decoding JSON from environment variable '{secretbuddy_env_var}': {e}")
  sys.exit(1)

# --------------------------------------------------------------------------------------------------
# print the list of Secretbuddy vars
print("#1 - List of Secretbuddy vars: ")
for k, v in secretbuddy_data_json["current"].items():
    print(f"\t{CYAN}{k}:{anonim(v)}{RESET}")

# --------------------------------------------------------------------------------------------------
# check if the environment variables match the Secretbuddy vars
# and print the differences
print("#2 - Config vars with different values than Secretbuddy vars: ", end="")
found = False
for k, v in secretbuddy_data_json["current"].items():
    env_value = os.getenv(k)
    if env_value is None:
      continue
    if v.replace('\n', '') != env_value.replace('\n', ''):
      if not found:
        print(end="\n")
        found = True
      print(f"\t{CYAN}{k}{RESET}<==>value:{CYAN}{anonim(env_value)}{RESET} secretbuddy:{CYAN}{anonim(v)}{RESET}")

if not found:
  print(f"{CYAN}None{RESET}")

# --------------------------------------------------------------------------------------------------
# check if there are any secret-like environment variables that are not in Secretbuddy vars
print("#3 - (secret) Config vars that do not exist in Secretbuddy vars: ", end="")
pattern = re.compile(r'(?i).*(secret|token|key|pass|auth|cred|certificate|cert|bearer|sign|salt).*')
found = False
for key, value in os.environ.items():
    #print("JLD: ", key)
    if key == secretbuddy_env_var:
      continue
    if pattern.match(key):
      #print("JLD matcheo")
      #print(secretbuddy_data_json["current"])
      if key not in secretbuddy_data_json["current"]:
        if not found:
          print(end="\n")
          found = True
        print(f"{CYAN}\t{key}: {value}{RESET}")

if not found:
  print(f"{CYAN}None{RESET}")

# --------------------------------------------------------------------------------------------------
# check if there are any Secretbuddy vars that are not in environment variables
# print the list of such vars
print("#4 - Secretbuddy vars that do not exist as Config var: ", end="")
os_envs_list = list(os.environ.keys())
found = False
for k, v in secretbuddy_data_json["current"].items():
    if k not in os_envs_list:
      if not found:
        print(end="\n")
        found = True
      print(f"{CYAN}\t{k}{RESET}")

if not found:
  print(f"{CYAN}None{RESET}")

# --------------------------------------------------------------------------------------------------
# print the Heroku command to unset all the Heroku config vars that Secretbuddy exports
print("#5 - Heroku command to unset all the Heroku config vars that Secretbuddy exports:")
cad = "heroku config:unset -a <app_name> "
for k, v in secretbuddy_data_json["current"].items():
   cad = cad + k + " "

print(f"\t{CYAN}{cad}{RESET}")